### ISSUE TITLE
Place users created from OIDC in a group automatically

### ISSUE THREAD

**Issue by dasGoogle** [ephios-dev/ephios#1070]
**Is your feature request related to a problem? Please describe.**
Currently, when a user signs in via OIDC, it appears that they are not in any group. Thus, the user has to be placed in that group manually which is not practical. 

**Describe the solution you'd like**
A user should be placed in a group automatically when they sign in via OIDC, either an automatic one line "OIDC Users" or one I can configure.

**Describe alternatives you've considered**
\-

**Additional context**
\-

**Comment by felixrindt** [comment]
Like I thought regarding custom SMTP servers, we could make OIDC configurable in the web interface and then add a field for initial groups there.

I don't like a "OIDC users" group because of the technical name and I wouldn't want it to be configured in the environment, as group setups tend to change (and hardcoding some object ID or group name seems weird).
