### ISSUE TITLE
Working hours do not respect individual shift times

### ISSUE THREAD

**Issue by jeriox** [ephios-dev/ephios#1165]
When a user has individual shift times, they still get the full shift length calculated for their working hour list.

**Comment by felixrindt** [comment]
Turns out people missed that they configured the individual end time for the date after the shift and missed it when reporting the bug. The added 24 hours where mistaken for coming from somewhere else, leading to the bug report.

The working hours calculation is correct. But of course this is a symptom for suboptimal UX on the UI for start and end times (for individual participation time just like for shift start end end).
