### ISSUE TITLE
Redesign login page on desktop with identity provider(s) activated

### ISSUE THREAD

**Issue by kubajznik** [ephios-dev/ephios#1355]
When an identity provider is activated the login page looks somewhat messy on desktop (mobile is just fine).

- order everything in column?
- make the fields narrower?
- add logo option for the identity provider?

<img width="1386" alt="image" src="https://github.com/user-attachments/assets/95c2202b-9e29-4b7d-bf97-42dc9911834c">
<img width="1623" alt="image" src="https://github.com/user-attachments/assets/c11a965a-d561-41bc-a38f-16ac3704dbfc">

**Comment by jeriox** [comment]
Hey, thanks for participating :D

Regarding the one with the form still visible: I totally see the point, especially because it is not aligned with the formfield. Maybe we could smth like

```
<Button Provider 1>
<Button Provider 1>

-------- or ------------

<Login Form>
```

Regarding the other variant: I felt that just a regular sized button looks a bit lost on the empty page, hence the full-width button. Not sure about a better option there

**Comment by felixrindt** [comment]
The container just needs to be narrower ^^

But I do think giving the whole view some love would be good. It's the entrance way to this product. We could show organization name maybe some nice decoration, and then the login controls.
