### ISSUE TITLE
Django 4.0 upgrade

### ISSUE THREAD

**Issue by felixrindt** [ephios-dev/ephios#578]
While hacking on https://github.com/ephios-dev/ephios/tree/django40 I stumpled upon a few hindrances.

* [x] django-recurrence is unmaintained and atm uncompatible, maybe move to https://github.com/niccokunzmann/python-recurring-ical-events ?
* [x] compressor is broken, because it is missing a release, and maintenance doesn't look promising, but I do really like the concept... 
* [x] https://github.com/django-polymorphic/django-polymorphic/pull/499 must be merged
* [x] django-webpush (GPL-licenced... so yeah we might need to drop it) is also broken: https://github.com/safwanrahman/django-webpush/issues/101
* [ ] dynamic-preferences has been bugging us too

**Comment by jeriox** [comment]
just read through the compressor stuff, they are preparing a 3.0 release which contains the fix for django4 along with other stuff. There have been several comments and a PR in the last few days, so I'm optimistic on that front

**Comment by jeriox** [comment]
regarding webpush: jazzband has something for that (https://github.com/jazzband/django-push-notifications), but in order to send WebPush messages it requires you to install pywebpush (https://github.com/web-push-libs/pywebpush), the same library used by django-webpush. And this library is also released under MPL, so we are not allowed to use it. Meanwhile their librarys for other languages are released unter MIT...

**Comment by jeriox** [comment]
compressor fixed in #646

**Comment by felixrindt** [comment]
webpush has been fixed, recurrence moved to jazzband, dynamic-prefs has seen some care...
